### ISSUE TITLE
Migrate to Github Actions

### ISSUE THREAD

**Issue by ktomk** [netz98/n98-magerun#1138]
Raised in #1133 by @cmuench, having an issue of it's own.

I ~~have plans to~~ do this as I currently already migrate in another project.

* [x] port/run Travis-CI build-jobs as Github Actions
* [x] reduce Travis-CI builds to `master` to verify migration baseline for some time
* [x] disable pull-request builds on travis-ci.org repository settings ([ref](https://travis-ci.org/github/netz98/n98-magerun/settings)).
* [x] re-integrate (parts of) [boilerplate workflow](https://github.com/actions/starter-workflows/blob/main/ci/php.yml)
* [x] use `$default-branch` macro
* [x] fix [`composer validate`](https://getcomposer.org/doc/03-cli.md#validate) (was not marking the build job red on validation warnings)
* [x] add test-setup job
* [x] streamline build files/scripts from `shared` folder (via #1149)
* [x] sunset circleci as not in use any longer (via #1152)
* [x] fix to build on master (missed in v2.1.0 - fixed but needs new release to confirm)
* [x] Sunset Circleci (via #1152)
* [x] streamline other build scripts (follow-up in part?) (via #1273)

Follow-Up Actions / Findings:
* [x] Restore Codecov (deactivated ca. two years ago) (via #1273)
* [x] The projects Composer validation is w/o dependencies (it fails, added with allowed failure to *PHP Composer* job) ([ref](https://github.com/netz98/n98-magerun/runs/1595449597?check_suite_focus=true#step:9:5), [ref](https://github.com/netz98/n98-magerun/runs/1595449597?check_suite_focus=true#step:9:16), [ref](https://github.com/netz98/n98-magerun/runs/1595449597?check_suite_focus=true#step:9:79)). Despite the warning, this does not (yet?) fail with composer v2 (at least not as dependency as this build job is using composer 2.0.8).

**Comment by cmuench** [comment]
For documentation... we have already this for n98-magerun2: https://github.com/netz98/n98-magerun2/tree/develop/.github/workflows
