### ISSUE TITLE
[WIP-PHP81] Checklist

### ISSUE THREAD

**Issue by sreichel** [netz98/n98-magerun#1275]
Based on https://github.com/cmuench/n98-magerun/tree/feature/php81

## Available commands:

- [ ] `completion`                         Dump the shell completion script
- [x] `help`                               Display help for a command
- [x] `install`                            Install magento
- [x] `list`                               List commands
- [x] `open-browser`                       Open current project in browser (experimental)
- [x] `script`                             Runs multiple n98-magerun commands
- [x] <s>`shell`                              Runs n98-magerun as shell</s> - _Removed with symfony3?_
- [ ] `uninstall`                          Uninstall magento (drops database and empties current folder or folder set via installationFolder)

### admin :heavy_check_mark: 
- [x] `admin:notifications`                Toggles admin notifications
- [x] `admin:user:change-password`         Changes the password of a adminhtml user.
- [x] `admin:user:change-status`           Set active status of an adminhtml user. If no option is set the status will be toggled.
- [x] `admin:user:create`                  Create admin user.
- [x] `admin:user:delete`                  Delete the account of a adminhtml user.
- [x] `admin:user:list`                    List admin users.
### cache :heavy_check_mark: 
- [x] `cache:clean`                        Clean magento cache
- [x] `cache:dir:flush`                    Flush (empty) Magento cache directory
- [x] `cache:disable`                      Disables magento caches
- [x] `cache:enable`                       Enables magento caches
- [x] `cache:flush`                        Flush magento cache storage
- [x] `cache:list`                         Lists all magento caches
- [x] `cache:report`                       View inside the cache
- [x] `cache:view`                         Prints a cache entry
### category :heavy_check_mark: 
- [x] `category:create:dummy`              Create a dummy category
### cms :heavy_check_mark: 
- [x] `cms:block:list`                     List all cms blocks
- [x] `cms:block:toggle`                   Toggle a cms block

### composer - _removed_
- [x] <s>`composer:diagnose`                  Diagnoses the system to identify common errors.</s>
- [x] <s>`composer:init`                      Creates a basic composer.json file in current directory.</s>
- [x] <s>`composer:install`                   [i] Installs the project dependencies from the composer.lock file if present, or falls back on the composer.json.</s>
- [x] <s>`composer:require`                   Adds required packages to your composer.json and installs them.</s>
- [x] <s>`composer:search`                    Searches for packages.</s>
- [x] <s>`composer:update`                    [u|upgrade] Upgrades your dependencies to the latest version according to composer.json, and updates the composer.lock file.</s>
- [x] <s>`composer:validate`                  Validates a composer.json and composer.lock.</s>
### config :heavy_check_mark: 
- [x] `config:delete`                      Deletes a store config item
- [x] `config:dump`                        Dump merged xml config
- [x] `config:get`                         Get a core config item
- [x] `config:search`                      Search system configuration descriptions.
- [x] `config:set`                         Set a core config item
### customer :heavy_check_mark: 
- [x] `customer:change-password`           Changes the password of a customer.
- [x] `customer:create`                    Creates a new customer/user for shop frontend.
- [x] `customer:create:dummy`              Generate dummy customers. You can specify a count and a locale.
- [x] `customer:delete`                    Delete Customer/s
- [x] `customer:info`                      Loads basic customer info by email address.
- [x] `customer:list`                      Lists customers
### db :heavy_check_mark: 
- [x] `db:console`                         [mysql-client] Opens mysql client by database config from local.xml
- [x] `db:create`                          Create currently configured database
- [x] `db:drop`                            Drop current database
- [x] `db:dump`                            Dumps database with mysqldump cli client
- [x] `db:import`                          Imports database with mysql cli client according to database defined in local.xml
- [x] `db:info`                            Dumps database informations
- [x] `db:maintain:check-tables`           Check database tables
- [x] `db:query`                           Executes an SQL query on the database defined in local.xml
- [x] `db:status`                          Shows important server status information or custom selected status values
- [x] `db:variables`                       Shows important variables or custom selected
### design :heavy_check_mark: 
- [x] `design:demo-notice`                 Toggles demo store notice for a store view
### dev :heavy_check_mark: 
- [x] `dev:class:lookup`                   Resolves a grouped class name
- [x] `dev:code:model:method`              Code annotations: Reads the columns from a table and writes the getter and setter methods into the class file for @methods.
- [x] `dev:console`                        Opens PHP interactive shell with initialized Mage::app() (Experimental)
- [x] `dev:email-template:usage`           Display database transactional email template usage
- [x] `dev:ide:phpstorm:meta`              Generates meta data file for PhpStorm auto completion (default version : 2019.1+)
- [x] `dev:log`                            Toggle development log (system.log, exception.log)
- [x] `dev:log:db`                         Turn on/off database query logging
- [x] `dev:log:size`                       Get size of log file
- [x] `dev:merge-css`                      Toggles CSS Merging
- [x] `dev:merge-js`                       Toggles JS Merging
- [x] `dev:module:create`                  Create and register a new magento module.
- [x] `dev:module:dependencies:from`       Show list of modules which depend on %s module
- [x] `dev:module:dependencies:on`         Show list of modules which given module depends on
- [x] `dev:module:disable`                 Disable a module or all modules in codePool
- [x] `dev:module:enable`                  Enable a module or all modules in codePool
- [x] `dev:module:list`                    List all installed modules
- [x] `dev:module:observer:list`           Lists all registered observers
- [x] `dev:module:rewrite:conflicts`       Lists all magento rewrite conflicts
- [x] `dev:module:rewrite:list`            Lists all magento rewrites
- [x] `dev:module:update`                  Update a Magento module.
- [x] `dev:profiler`                       Toggles profiler for debugging
- [x] `dev:report:count`                   Get count of report files
- [x] `dev:setup:script:attribute`         Creates attribute script for a given attribute code
- [x] `dev:symlinks`                       Toggle allow symlinks setting
- [x] `dev:template-hints`                 Toggles template hints
- [x] `dev:template-hints-blocks`          Toggles template hints block names
- [x] `dev:theme:duplicates`               Find duplicate files (templates, layout, locale, etc.) between two themes.
- [x] `dev:theme:info`                     Displays settings of current design on particular store view
- [x] `dev:theme:list`                     Lists all available themes
- [x] `dev:translate:admin`                Toggle inline translation tool for admin
- [x] `dev:translate:export`               Export inline translations
- [x] `dev:translate:set`                  Adds a translation to core_translate table. Globally for locale
- [x] `dev:translate:shop`                 Toggle inline translation tool for shop
### eav :heavy_check_mark: 
- [x] `eav:attribute:create-dummy-values`  Create a dummy values for dropdown attributes
- [x] `eav:attribute:list`                 Lists all EAV attributes
- [x] `eav:attribute:remove`               Removes attribute for a given attribute code
- [x] `eav:attribute:view`                 View informations about an EAV attribute
### index :heavy_check_mark: 
- [x] `index:list`                         Lists all magento indexes
- [x] `index:reindex`                      Reindex a magento index by code
- [x] `index:reindex:all`                  Reindex all magento indexes
### local-config :heavy_check_mark: 
- [x] `local-config:generate`              Generates local.xml config
### media :heavy_check_mark: 
- [x] `media:cache:image:clear`            Clears image cache
- [x] `media:cache:jscss:clear`            Clears JS/CSS cache
- [x] `media:dump`                         Creates an archive with content of media folder.
### script :heavy_check_mark: 
- [x] `script:repo:list`                   Lists all scripts in repository
- [x] `script:repo:run`                    Run script from repository
### sys :heavy_check_mark: 
- [x] `sys:check`                          Checks Magento System
- [x] `sys:cron:history`                   Last executed cronjobs with status.
- [x] `sys:cron:list`                      Lists all cronjobs
- [x] `sys:cron:run`                       Runs a cronjob by job code
- [x] `sys:info`                           Prints infos about the current magento system.
- [x] `sys:maintenance`                    Toggles maintenance mode.
- [x] `sys:modules:list`            List all installed modules
- [x] `sys:setup:change-version`           Change module setup resource version
- [x] `sys:setup:compare-versions`         Compare module version with core_resource table.
- [x] `sys:setup:incremental`              List new setup scripts to run, then runs one script
- [x] `sys:setup:remove`                   Remove module setup resource entry
- [x] `sys:setup:run`                      Runs all new setup scripts.
- [x] `sys:store:config:base-url:list`     Lists all base urls
- [x] `sys:store:list`                     Lists all installed store-views
- [x] `sys:url:list`                       Get all urls.
- [x]  `sys:website:list`                   Lists all websites

**Comment by sreichel** [comment]
## For next PR ...

https://github.com/cmuench/n98-magerun/pull/87

### Tasks

- [x] `index:reindex` ... fix output
- [x] `sys:check` .... is incomplete. Ext `intl` is required _now_

### Errors

- [x] `admin:user:change-password`
- [x] `customer:create:dummy`
- [x] `customer:info`
- [x] `db:maintain:check-tables`
- [x] `design:demo-notice`
- [x] `dev:module:dependencies:from`
- [x] `dev:module:dependencies:on`
- [x] `dev:module:observer:list`
- [x] `eav:attribute:view`
- [x] `script:repo:run`
- [x] `sys:setup:run`

**Comment by addison74** [comment]
A real work to be appreciated to keep this tool up to date which was heavily used during Magento 1. OpenMage continues Magento 1 and doesn't stop at being an LTS.

**Comment by sreichel** [comment]
@cmuench PR is ready.

Did not touch composer related commands. Do we still need them?

Install/Uninstall needs to be tested by someone else (does not work in my DDEV environment)

Unittests have to be adjusted. Some help would be nice here :)

**Comment by cmuench** [comment]
@sreichel I do not work with Magento 1 anymore on a daily base. Maybe we should remove the Composer library from Magerun 1.
Removing means that we have to replace also the internal downloader logic which is using the Composer packages.
I already did that for Magerun 2 to prevent conflicts with Symfony components etc.

**Comment by sreichel** [comment]
It would have been easier to backport magerun2 :rofl: 

Install/CI fails b/c composer dowload does not work. @cmuench can we/you backport install cmd from magerun2?

**Comment by sreichel** [comment]
## For next PR ...

Backport from n89-magerun2 ...

### Updates

- [x] `twig/twig` v3

### Tasks

- [ ] `completion` .... Shell not detected, Symfony shell completion only supports "bash").
- [ ] `admin:user:change-password` ... add check password length
- [ ] `cms:block:toggle` ... add suggestions
- [ ] `customer:change-password` ... dont break for short passwords, ask again
- [ ] `db:create` ... dont break for short passwords, ask again
- [ ] `dev:code:model:method` ... does not work for eav (`catalog/product`, ...)
- [ ] `eav:attribute:create-dummy-values` ... error displayed, but works

### Errors

- [ ] `open-browser`
- [ ] `script`

**Comment by cmuench** [comment]
@sreichel I tested the installation on my local machine and it works in the provided ddev environment. Currently I don't know why it's failing in CI.
Did the install fail on your machine?

**Comment by sreichel** [comment]
@cmuench  package download does not work for me too. Install dir `magento` is created with subdir `vendor/compoer`, but there are no magento files ...

```
In InstallCommand.php line 1046:
                                                                                                   
  Installation failed (Exit code 1). Could not open input file: /var/www/html/magento/install.php  
```

**Comment by cmuench** [comment]
@cmuench ok, interesting. We will find the issue :-)

**Comment by cmuench** [comment]
@sreichel I can reproduce it! That's good.

**Comment by cmuench** [comment]
@sreichel I guess Composer 2.2 is not compatible. I will try to backport the downloader logic from Magerun 2.

**Comment by cmuench** [comment]
@sreichel I started to backport the installer command.
It requires also the backport of the sub-command logic.
My WIP is pushed to the branch. 

The main issue is that the installer of n98-magerun2 works stricly with Composer packages.
The config in the config.yaml looks like this:

```yaml
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: mage-os-2.4.5-p1
        package: magento/project-community-edition
        version: 2.4.5-p1
        options:
          repository-url: https://mirror.mage-os.org
```

In n98-magerun1 we have a different structure:

```yaml
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: openmage-20.0.14
        version: 20.0.14
        dist:
          url: https://github.com/OpenMage/magento-lts/archive/v20.0.14.zip
          type: zip
          shasum: 15172228925d2f03db00712e591f14b15210bea1
        extra:
          sample-data: sample-data-1.9.2.4
```

Currently we use the internal Composer library to handle that.
Sadly I do not see a good way to call an external Composer binary and feed it with the information of the package.
I could replace the logic with a simple download and extract, but this would break a lot of automations.
If you have a good idea. Let me know.

**Comment by sreichel** [comment]
@cmuench can we use https://github.com/firegento/magento for composer installable packages instead of magento-mirror?

**Comment by cmuench** [comment]
@sreichel Installer is now working in the Github Actions.
Next a lot of tests have to be fixed.
Currently 43 tests are failing.

**Comment by cmuench** [comment]
Seems that most of the tests are currently not compatible with the new console "ask" method.

**Comment by sreichel** [comment]
@cmuench thanks for working on this. 

Unfortunately my ddev env has some problems ... https://stackoverflow.com/q/76366191/5703627

My changes are very similar to magerun2, may we can reuse some code for unit tests?

**Comment by sreichel** [comment]
@cmuench we also have to fix sample data intstall.

I can create a repo from @Vinai (or my own) sample data to allow install via composer.

**Comment by sreichel** [comment]
> Next a lot of tests have to be fixed.

@cmuench Working on this next days. Will also update to phpunit 9.

**Comment by alexherbs** [comment]
Hello, 

i wanted to mention following errors which occured during switching from OpenMage PHP7.4 to PHP8.1, maybe its useful for your checklist (n98-magerun --version: 2.3.0):

2023-08-15T03:32:21+00:00 ERR (3): Deprecated functionality: Return type of N98\Magento\Modules::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice  in phar:///usr/bin/n98-magerun.phar/src/N98/Magento/Modules.php on line 96

2023-08-15T03:32:21+00:00 ERR (3): Deprecated functionality: Return type of N98\Magento\Modules::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice  in phar:///usr/bin/n98-magerun.phar/src/N98/Magento/Modules.php on line 108

2023-08-15T06:05:29+00:00 ERR (3): Deprecated functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated  in phar:///usr/bin/n98-magerun.phar/src/N98/Magento/Command/System/Url/ListCommand.php on line 83

**Comment by cmuench** [comment]
@sreichel Spent some time to fix the tests and already did the upgrade to PHPUnit 9.
I had to skip some tests because too much changed in PHPUnit which needs a lot of more time to refactor.
Most of the tests are running fine.

**Comment by cmuench** [comment]
@sreichel I merged the current state to develop branch. I did this to get the Github Actions running. The old Ubuntu Version in the Github Actions was not supported anymore.

**Comment by cmuench** [comment]
@sreichel Phar build is also fixed and files.magerun.net is updated with the latest dev version if n98-magerun1.
This means that we can now test in a real OpenMage installation. Sadly I have no real OpenMage project to test.

**Comment by cmuench** [comment]
@sreichel sample data "no" should work in the next minutes. Pushed a fix to develop branch.

**Comment by cmuench** [comment]
@sreichel You ask about we can handle the DB port... I used port 3306 in the container in the install command.
This is OK inside the container. The dynamic port numbers are only for the port forwording to the host.
I use the db container and create a separate db for each instance.
That works with the PhpStorm ddev integration plugin without any issue.

**Comment by cmuench** [comment]
@sreichel I added functional tests to the Github Actions. This helps to find issues which cannot be found in the Unit Tests.
We test Magento 1.9 and OpenMage 20.0.20.

**Comment by cmuench** [comment]
@sreichel I will extend the OpenMage Build with a build matrix.
I test it in this PR #1297.
It will also test with MySQL 5.7 and MySQL 8.0

**Comment by addison74** [comment]
@sreichel - Could you please allocate some time to complete this checklist? For everyone who uses OpenMage it would be a gift to be able to continue using n98-magerun. We could also add some custom commands to DDEV as you wanted.

**Comment by cmuench** [comment]
@sreichel @ADDISON74 The develop version is already "green" in all tests. Feel free to test it in a real project. I sadly have not any real OpenMage project.

**Comment by sreichel** [comment]
@ADDISON74 i will update during next days.

**Comment by sreichel** [comment]
@cmuench how about to drop support for php < 8.1 for v3?

v2.3 works up to php 8.0, right? We dont need any backward compatibilty and could make use of php 8.1 features.

**Comment by sreichel** [comment]
@cmuench work on some cleanup ... (and phpstan L9)

- do we still need M2 related switches?
- can we drop EE-related code? EE does not work with php8.

**Comment by cmuench** [comment]
@sreichel thanks for working on the finalization of the release.
About dropping the PHP 7.4 support. We should wait with that. I am very conservative with that. The n98-magerun2 version is still compatible with 7.4.
There are a lot of automatization downloading and executing n98-magerun. We need to plan and announce this.

In the EE command should be a check. We can add a constraint to current the PHP version there and skip the tests

The M2 related switches are to provide a hint if the wrong version is used. I think after 10 years we can remove that.

**Comment by sreichel** [comment]
@cmuench do we need to support something below php8.1 for v3?

For php7-8.0 you can still use v2.3.

For a php8.1 release we can update to symfony 6.4.

EE commands can be moved into an add-on. I know there are commands the are EE-only snare disabled for CE, but others that have different behavior inside the command. This causes some problems with phpstan, that can't find EE-related classes.

However ... I have to split my work into smaller PRs ... hope it's okay to not doing it in one big PR.

**Comment by cmuench** [comment]
@sreichel The plan is that the current release is still compatible with the latest Magento Open Source 1.9 with PHP 7.4. Let's bring first the build in production. I want to stay on Symfony LTS releases which is currently 5.4.
Next LTS is 6.4. The 6.3 release will have the EOL soon.

**Comment by sreichel** [comment]
Okay. :)

What about EE-commands? Is it fine to move them into a separate repo?

(already removed that code for phpstan and have to revert it ...)

**Comment by cmuench** [comment]
@sreichel They will never be called and registered in OpenMage due to this code:

```php
 public function isEnabled()
 {
     return $this->getApplication()->isMagentoEnterprise();
 }
 ```
We can just ignore them and remove the test setup.
I am defensive, because we do not know if someone is still running Magento EE. I guess it's a license problem if someone does.
I am not sure that the best procedure here is. It's also fine to drop the support for Magento EE here.

**Comment by sreichel** [comment]
@cmuench i know, but im sure there are commands that work for EE and CE, but have different behavior inside the command. (e.g. create admin user - adding roles)

**Comment by cmuench** [comment]
We can drop support for EE this release. And deprecate then the old Magento CE 1.9 for the next major release.
Than we can prepare the people and make the tool only compatible with OpenMage.

**Comment by sreichel** [comment]
Okay ... PRs incoming next days :)

**Comment by sreichel** [comment]
> @sreichel - Could you please allocate some time to complete this checklist? For everyone who uses OpenMage ...

Maybe some OM users want to join for help? At least with tests?

**Comment by ADDISON74** [comment]
Create a request in the Discussions section of OpenMage. There are quite a few who use N98-magerun, theoretically they could help.

**Comment by sreichel** [comment]
# Final tests:

- added strict types
- added type hints for parameters/return values
- simplified code for list commands (added a new interface)
- prepared for symfony 6.1 (php >8.1)
- pass phpstan level 9

## Available commands:

- [ ] `completion`                         Dump the shell completion script
- [ ] `help`                               Display help for a command
- [ ] `install`                            Install magento
- [ ] `list`                               List commands
- [ ] `open-browser`                       Open current project in browser (experimental)
- [ ] `script`                             Runs multiple n98-magerun commands
- [ ] <s>`shell`                              Runs n98-magerun as shell</s> - _Removed with symfony3?_
- [ ] `uninstall`                          Uninstall magento (drops database and empties current folder or folder set via installationFolder)

### admin
- [ ] `admin:notifications`                Toggles admin notifications
- [ ] `admin:user:change-password`         Changes the password of a adminhtml user.
- [ ] `admin:user:change-status`           Set active status of an adminhtml user. If no option is set the status will be toggled.
- [ ] `admin:user:create`                  Create admin user.
- [ ] `admin:user:delete`                  Delete the account of a adminhtml user.
- [ ] `admin:user:list`                    List admin users.
### cache
- [ ] `cache:clean`                        Clean magento cache
- [ ] `cache:dir:flush`                    Flush (empty) Magento cache directory
- [ ] `cache:disable`                      Disables magento caches
- [ ] `cache:enable`                       Enables magento caches
- [ ] `cache:flush`                        Flush magento cache storage
- [ ] `cache:list`                         Lists all magento caches
- [ ] `cache:report`                       View inside the cache
- [ ] `cache:view`                         Prints a cache entry
### category
- [ ] `category:create:dummy`              Create a dummy category
### cms
- [ ] `cms:block:list`                     List all cms blocks
- [ ] `cms:block:toggle`                   Toggle a cms block

### composer - _removed_
- [ ] <s>`composer:diagnose`                  Diagnoses the system to identify common errors.</s>
- [ ] <s>`composer:init`                      Creates a basic composer.json file in current directory.</s>
- [ ] <s>`composer:install`                   [i] Installs the project dependencies from the composer.lock file if present, or falls back on the composer.json.</s>
- [ ] <s>`composer:require`                   Adds required packages to your composer.json and installs them.</s>
- [ ] <s>`composer:search`                    Searches for packages.</s>
- [ ] <s>`composer:update`                    [u|upgrade] Upgrades your dependencies to the latest version according to composer.json, and updates the composer.lock file.</s>
- [ ] <s>`composer:validate`                  Validates a composer.json and composer.lock.</s>
### config
- [ ] `config:delete`                      Deletes a store config item
- [ ] `config:dump`                        Dump merged xml config
- [ ] `config:get`                         Get a core config item
- [ ] `config:search`                      Search system configuration descriptions.
- [ ] `config:set`                         Set a core config item
### customer
- [ ] `customer:change-password`           Changes the password of a customer.
- [ ] `customer:create`                    Creates a new customer/user for shop frontend.
- [ ] `customer:create:dummy`              Generate dummy customers. You can specify a count and a locale.
- [ ] `customer:delete`                    Delete Customer/s
- [ ] `customer:info`                      Loads basic customer info by email address.
- [ ] `customer:list`                      Lists customers
### db
- [ ] `db:console`                         [mysql-client] Opens mysql client by database config from local.xml
- [ ] `db:create`                          Create currently configured database
- [ ] `db:drop`                            Drop current database
- [ ] `db:dump`                            Dumps database with mysqldump cli client
- [ ] `db:import`                          Imports database with mysql cli client according to database defined in local.xml
- [ ] `db:info`                            Dumps database informations
- [ ] `db:maintain:check-tables`           Check database tables
- [ ] `db:query`                           Executes an SQL query on the database defined in local.xml
- [ ] `db:status`                          Shows important server status information or custom selected status values
- [ ] `db:variables`                       Shows important variables or custom selected
### design
- [ ] `design:demo-notice`                 Toggles demo store notice for a store view
### dev
- [ ] `dev:class:lookup`                   Resolves a grouped class name
- [ ] `dev:code:model:method`              Code annotations: Reads the columns from a table and writes the getter and setter methods into the class file for @methods.
- [ ] `dev:console`                        Opens PHP interactive shell with initialized Mage::app() (Experimental)
- [ ] `dev:email-template:usage`           Display database transactional email template usage
- [ ] `dev:ide:phpstorm:meta`              Generates meta data file for PhpStorm auto completion (default version : 2019.1+)
- [ ] `dev:log`                            Toggle development log (system.log, exception.log)
- [ ] `dev:log:db`                         Turn on/off database query logging
- [ ] `dev:log:size`                       Get size of log file
- [ ] `dev:merge-css`                      Toggles CSS Merging
- [ ] `dev:merge-js`                       Toggles JS Merging
- [ ] `dev:module:create`                  Create and register a new magento module.
- [ ] `dev:module:dependencies:from`       Show list of modules which depend on %s module
- [ ] `dev:module:dependencies:on`         Show list of modules which given module depends on
- [ ] `dev:module:disable`                 Disable a module or all modules in codePool
- [ ] `dev:module:enable`                  Enable a module or all modules in codePool
- [ ] `dev:module:list`                    List all installed modules
- [ ] `dev:module:observer:list`           Lists all registered observers
- [ ] `dev:module:rewrite:conflicts`       Lists all magento rewrite conflicts
- [ ] `dev:module:rewrite:list`            Lists all magento rewrites
- [ ] `dev:module:update`                  Update a Magento module.
- [ ] `dev:profiler`                       Toggles profiler for debugging
- [ ] `dev:report:count`                   Get count of report files
- [ ] `dev:setup:script:attribute`         Creates attribute script for a given attribute code
- [ ] `dev:symlinks`                       Toggle allow symlinks setting
- [ ] `dev:template-hints`                 Toggles template hints
- [ ] `dev:template-hints-blocks`          Toggles template hints block names
- [ ] `dev:theme:duplicates`               Find duplicate files (templates, layout, locale, etc.) between two themes.
- [ ] `dev:theme:info`                     Displays settings of current design on particular store view
- [ ] `dev:theme:list`                     Lists all available themes
- [ ] `dev:translate:admin`                Toggle inline translation tool for admin
- [ ] `dev:translate:export`               Export inline translations
- [ ] `dev:translate:set`                  Adds a translation to core_translate table. Globally for locale
- [ ] `dev:translate:shop`                 Toggle inline translation tool for shop
### eav
- [ ] `eav:attribute:create-dummy-values`  Create a dummy values for dropdown attributes
- [ ] `eav:attribute:list`                 Lists all EAV attributes
- [ ] `eav:attribute:remove`               Removes attribute for a given attribute code
- [ ] `eav:attribute:view`                 View informations about an EAV attribute
### index
- [ ] `index:list`                         Lists all magento indexes
- [ ] `index:reindex`                      Reindex a magento index by code
- [ ] `index:reindex:all`                  Reindex all magento indexes
### local-config
- [ ] `local-config:generate`              Generates local.xml config
### media
- [ ] `media:cache:image:clear`            Clears image cache
- [ ] `media:cache:jscss:clear`            Clears JS/CSS cache
- [ ] `media:dump`                         Creates an archive with content of media folder.
### script
- [ ] `script:repo:list`                   Lists all scripts in repository
- [ ] `script:repo:run`                    Run script from repository
### sys
- [ ] `sys:check`                          Checks Magento System
- [ ] `sys:cron:history`                   Last executed cronjobs with status.
- [ ] `sys:cron:list`                      Lists all cronjobs
- [ ] `sys:cron:run`                       Runs a cronjob by job code
- [ ] `sys:info`                           Prints infos about the current magento system.
- [ ] `sys:maintenance`                    Toggles maintenance mode.
- [ ] `sys:modules:list`            List all installed modules
- [ ] `sys:setup:change-version`           Change module setup resource version
- [ ] `sys:setup:compare-versions`         Compare module version with core_resource table.
- [ ] `sys:setup:incremental`              List new setup scripts to run, then runs one script
- [ ] `sys:setup:remove`                   Remove module setup resource entry
- [ ] `sys:setup:run`                      Runs all new setup scripts.
- [ ] `sys:store:config:base-url:list`     Lists all base urls
- [ ] `sys:store:list`                     Lists all installed store-views
- [ ] `sys:url:list`                       Get all urls.
- [ ]  `sys:website:list`                   Lists all websites

**Comment by sreichel** [comment]
@cmuench killed my work with `composer require ...` ... LOL

I'll try to split my PRs into small chunks ... sorry for extra work, but maybe PRs are much more clear.

**Comment by sreichel** [comment]
@cmuench think we can close this.

All my changes in pipeline are only code style improvments. No functional changes.

I'll provide updates step by step, but i thinks its ready to make a php81 release.
